### ISSUE TITLE
setup_password is not persisted

### ISSUE THREAD

**Issue by cdauth** [hardware/postfixadmin#10]
`setup_password` is saved in `/postfixadmin/config.inc.php`, which is not persisted when the container is updated/recreated, so it is reset to an empty password. This is a security risk, as it enables users to create an admin account.

The best solution that I can see is to set `setup_password` to some bogus by default so that `setup.php` cannot be used, and make the `setup` script ask for a plaintext password, whose hash is then saved in `config.inc.php`.

**Comment by hardware** [comment]
`$CONF['configured'] = true;` is useless ?

**Comment by hardware** [comment]
You can't create an admin account without setup_password properly configured server-side so there is not security flaw.

**Comment by cdauth** [comment]
Ah, true, I forgot that setting the setup password only gives you a hash that you should put in the config…
