### ISSUE TITLE
Password hashing does not work

### ISSUE THREAD

**Issue by cdauth** [hardware/postfixadmin#11]
I don’t know how it’s possible that this (apparently) works for other people, but for me I cannot log into postfixadmin because the password hashing does not work. The function `pacrypt()` in `/postfixadmin/functions.inc.php` makes the following call in line 964:

```php
$dovepasstest = " -t " . escapeshellarg($pw_db);
```

This will generate a command like this:

```bash
/usr/bin/doveadm pw -s SHA256-CRYPT -t '$5$abcdef'
```

This will fail with this error message:

```
Fatal: Missing {scheme} prefix from hash
```

It can be fixed by changing the line to:

```php
$dovepasstest = " -t " . escapeshellarg("{{$method}}$pw_db");
```

for example using the command:

```bash
sed -ri /postfixadmin/functions.inc.php -e 's/escapeshellarg\(\$pw_db\)/escapeshellarg("{{\$method}}\$pw_db")/'
```

A temporary workaround is to include that command in the cmd parameter, for example using docker-compose:

```yaml
command:
    - sh
    - -c
    - sed -ri /postfixadmin/functions.inc.php -e 's/escapeshellarg\(\$$pw_db\)/escapeshellarg("{{\$$method}}\$$pw_db")/' && run.sh
```

**Comment by hardware** [comment]
Maybe it's a doveadm bug, i don't have this error. What is your docker filesystem ?

http://wiki2.dovecot.org/Tools/Doveadm/Pw

```
-s scheme
  The password scheme which should be used to generate the hashed password. By default the CRAM-MD5 scheme will be used. It is also possible to append an encoding suffix to the scheme. Supported encoding suffixes are: .b64, .base64 and .hex.
  See also http://wiki2.dovecot.org/Authentication/PasswordSchemes for more details about password schemes.
```

Can you post your problem here : https://sourceforge.net/p/postfixadmin/discussion/676076/ ?

**Comment by cdauth** [comment]
Strange, if I use the same Dockerfile as you, I suppose I also use the same version of doveadm. What do your password hashes look like, are they different than mine?

**Comment by hardware** [comment]
They are prefixed by `{SHA512-CRYPT}$6$`

Can you give me some context information with `docker info` command ?
