### ISSUE TITLE
Port not accessible

### ISSUE THREAD

**Issue by hsaklecha** [hardware/postfixadmin#13]
I have deployed this server on cent os and opened the port 8888 for my network, but i am not able to access the port, niether i see it opened on my machine, is there any setting to be done with this docker container in docker-compose.yml

**Comment by hardware** [comment]
Because this is not (by default) an external port. This port is used by your reverse proxy.

More information : https://github.com/hardware/mailserver/wiki/Reverse-proxy-configuration

```
location / {
    proxy_pass http://postfixadmin:8888;
    include /etc/nginx/conf/proxy_params;
}
```

**Comment by hsaklecha** [comment]
And how can i connect this postfixadmin to mail server running in another docker container where should i provide the path

**Comment by hardware** [comment]
You don't need to connect this container to mail server, MariaDB is used for this purpose.

**Comment by hsaklecha** [comment]
Then i get an error for login page i cannot access it i can send you my docker-compose.yml, i have my docker and maria db running and mysql instance too running and all up, but when i hit on 8888, i get an error on login page and it is not loading

**Comment by hardware** [comment]
> i can send you my docker-compose.yml

Yes.

**Comment by hsaklecha** [comment]
postfixadmin:
  image: hardware/postfixadmin
  container_name: postfixadmin
  domainname: domain.tld
  hostname: mail
  links:
    - mariadb:mariadb

  environment:
    - DBHOST=localhost:3306
    - DBUSER=admin
    - DBNAME=postfix
    - DBPASS=admin
    - UID=991



mariadb:
  image: mariadb:10.1
  container_name: mariadb
  volumes:
    - /mnt/docker/mysql/db:/var/lib/mysql
  environment:
    - MYSQL_ROOT_PASSWORD=admin
    - MYSQL_DATABASE=postfix
    - MYSQL_USER=admin
    - MYSQL_PASSWORD=admin

**Comment by hardware** [comment]
If you really want to access postfixadmin container with an external port, you can add this :

```yml
postfixadmin:
  ports:
    - "8888:8888"

# URI : http://IPADDR:8888
```



Or you can use nginx as reverse proxy :

```
location / {
  proxy_pass http://postfixadmin:8888;
  include /etc/nginx/conf/proxy_params;
}
```

**Comment by hsaklecha** [comment]
I have use docker run command and passed port with -p and now i can access it from server where i have hosted it, now how to use the login page, as when i hit on login page i get an error for help page.


Error :
DEBUG INFORMATION:
Connect: Network unreachable

how to access logs for this?
And do we need a domain which will be used to send mail and where to configure if it isnt the case i can install it on my machine rather then server where mail server is hosted which is using that domain and can send mails. ?

**Comment by hardware** [comment]
Please read carefully the wiki and readme.md.

https://github.com/hardware/mailserver/wiki/Reverse-proxy-configuration
https://github.com/hardware/mailserver/wiki/Postfixadmin-initial-configuration
https://github.com/hardware/postfixadmin/blob/master/README.md
https://github.com/hardware/mailserver/blob/master/README.md

**Comment by hsaklecha** [comment]
We need a mailserver connection to manage domains, this postfix admin is accessing which mail server, how do i connect it to my own mail server ?

**Comment by hardware** [comment]
```yml
# docker-compose.yml
extra_hosts:
 - "mariadb:xx.xx.xx.xx"
```
**xx.xx.xx.xx** : IP address of your MariaDB/MySQL server.
