### ISSUE TITLE
Discussion: Official docker image

### ISSUE THREAD

**Issue by navossoc** [hardware/postfixadmin#19]
It looks like postfixadmin will have an official image available anytime soon.
https://github.com/postfixadmin/docker

Is there any thought about using the official image in the future?

Not that it really makes a difference to me, but maybe just to simplify your life and be one less project for you manage.

What do you think about it?

[]'s

**Comment by hardware** [comment]
If this image is maintained (which does not seem to be the case), yes why not. But postfixadmin is very easy to maintain. It does not take much time.

**Comment by navossoc** [comment]
Great, I did a fork of this repository and set custom values on `quota_multiplier` and `page_size` variables.

I think I can get some time tomorrow and do a pull request putting this extra configurations on environment variables.

Are you willing to accept it? It is a simple modification.

It will be one less thing for me to keep track 👍 

Thanks.
